# Generated by Django 5.0.4 on 2024-04-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SMTPConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EMAIL_HOST", models.CharField(max_length=100)),
                ("EMAIL_PORT", models.IntegerField()),
                ("EMAIL_HOST_USER", models.EmailField(max_length=254)),
                ("EMAIL_HOST_PASSWORD", models.CharField(max_length=100)),
            ],
        ),
    ]
